### ISSUE TITLE
Not working with latest A-Frame 1.0.3

### ISSUE THREAD

**Issue by planetvoodoo** [wizgrav/aframe-effects#25]
Eagerly awaiting an update for this. Sadly no longer working with latest versions of A-Frame.

**Comment by Firepal** [comment]
Feels like this repo has been abandoned...

**Comment by Firepal** [comment]
(ok maybe that's a liiiitle harsh)

**Comment by tomdeleu** [comment]
Harsh, but the truth it seems, unfortunately.  Not a lot of activity in here.

Would love to help out if I could, but I'm not skilled enough yet in ThreeJS to take on something like this.

**Comment by Firepal** [comment]
@tomdeleu In October, the maintainer said they were refactoring the component. We're in late February and no dice...

**Comment by dirkk0** [comment]
I am still hoping he's on it.

Anyway, there's another lib here:
https://github.com/vanruesc/postprocessing

But unfortunately, it doesn't work in VR either.
But it works with 1.0.4:
https://github.com/vanruesc/postprocessing

**Comment by Firepal** [comment]
@dirkk0 I mean, that's just three.js's post-processing module. I think three.js demonstrates it in official examples, actually.

Point is, A-Frame is VR-focused before anything else, and that makes the three.js post-processing module pretty much useless for A-Frame.

**Comment by dirkk0** [comment]
Agreed, but the example I provided is in A-Frame and the author is aware of this (but didn't solve it yet):
https://github.com/vanruesc/postprocessing/issues/85#issuecomment-401575356

**Comment by dirkk0** [comment]
I made an effort to fix aframe-effects, which failed unsurprisingly.

I managed to get rid of the renderTarget, forceClear and getSize error messages as suggested in #19 , but other than it's still not working.

Maybe someone else with better ideas (or even @wizgrav ?) can jump in and pick up the ball from there:
https://glitch.com/edit/#!/spectacular-fishy-ocarina?path=index.html:8:5

**Comment by planetvoodoo** [comment]
@wizgrav is harder to track down than Satoshi Nakamoto. Some kick ass effects in here that I'm itching to use! …---…

**Comment by kfarr** [comment]
Here is a relevant pull request and discussion on threejs repo: https://github.com/mrdoob/three.js/pull/18846

**Comment by Firepal** [comment]
@kfarr Not exactly related to this project, but yeah. Been following it too

**Comment by planetvoodoo** [comment]
> Anyway, there's another lib here:
> https://github.com/vanruesc/postprocessing
> 
> But unfortunately, it doesn't work in VR either.
> But it works with 1.0.4:
> https://gentle-glitter-close.glitch.me/

@dirkk0 the camera always appears too 'zoomed' in and near/far settings don't seem to help as some objects are missing from the background. Any idea on how to resolve this? I got all excited at finally seeing some post processing work after all these months!

What do I have to do to get a reliable, easy to use effects library working?! It makes such a big difference to the look and feel of my work. So frustrating... had to delay a lot of projects recently.

**Comment by wizgrav** [comment]
as @kfarr  has pointed out here https://github.com/mrdoob/three.js/pull/18846 three is fundamentaly broken in regards to post proc(and other things) and their devs are unwilling and/or unable to fix it or even assess solutions from third parties. Regressions are the order of the day and I can't keep providing patched versions of the library for my clients + I may not be able to even do that if the regression is severe. They are totally untrustworthy and as  I don't like leaving people in the dark I have to state that I won't bother anymore, if you want to do serious dev I suggest you all to switch to unity like I did

**Comment by dirkk0** [comment]
You can also switch to BabylonJS which I like more and more.
https://glitch.com/edit/#!/babylon-glow-vr

**Comment by wizgrav** [comment]
@dirkk0 I thought about it and having even semi-official support from Microsoft is tempting but I decided to get off the web all together. It just doesn't make professional sense for VR development when you can't target PSVR which is half the market. Also seeing mozilla who made WebVR in the first place, drop it is not a good sign. Anyway I don't want to force feed my opinions on others. I made my choice and took the opportunity in the lockdown to invest on unity so I'll stick with that for the time being

**Comment by planetvoodoo** [comment]
Thanks @dirkk0, will explore it in detail soon. I managed to get something rocking using https://jsfiddle.net/awrof47v/ which stopped working as soon as more than one camera was used. Got around it by using one camera and updating position / rotation. 

And I'm just glad you're safe and well @wizgrav! I'd not seen any online activity for a long time.

I have a vision for the future, and I'm preparing for the user habits / devices of tomorrow. As fun as it is, PSVR doesn't feature in where I believe all this will eventually end up, unless they launch portable / wearable PS in 2024. The shareability of web based art / applications is a massive appeal.

**Comment by dirkk0** [comment]
@wizgrav totally understandable and Unity is the (or let's say one) right decision if you target VR games for consoles.
I bought Unity several times back in the days when it was 1500 bucks or so, but now I neither like the subscription model that they have nor the update politics. But, again, the right decision if you want to get things done.
My personal project targets the Quest at the moment and if I don't stick with A-Frame, I'll consider to switch either to Babylon or (also tempting) Godot.

**Comment by wizgrav** [comment]
@dirkk0 it's the right choice if you target VR games in general, not just consoles. It is actually impossible to publish a game with HTML as you need integration with the store platforms to do the entitlement checks and various other things.

You don't actually need to pay the unity subscription now, if you're not making good money out of it and you don't really miss functionality if you don't. I did as it's ~50 pounds/month which is bearable and you get a professional tool. If three.js charged even 50 cents to use it, its user base would just disappear

**Comment by dirkk0** [comment]
Good points.
My last remark would be that Sidequest seems to support WebXR apps for their store:
https://www.reddit.com/r/WebVR/comments/giuwq4/get_your_webxr_experience_on_sidequest_with_first/

**Comment by wizgrav** [comment]
I love sidequest and use it regularly to test builds but I'm not very optimistic about its future. Recently facebook said they will provide an alternative way to distribute apps on the quest. Don't be surprised if they kill sidequest to replace it with their own thing. Zuckie is a control freak, you don't get to piggyback on his toys for long

**Comment by dirkk0** [comment]
I agree.
I think I speak for most of the people in this thread, when I say we really
appreciate the work you sunk in this.
Thanks for making this and for giving these insights.
