### ISSUE TITLE
in win10 have some problem

### ISSUE THREAD

**Issue by mike-hor** [wizgrav/aframe-effects#5]
http://play.mengxw.cn/miku_jljt.html
win7 have a good effect but in win10 you can look it have double shadow,

**Comment by wizgrav** [comment]
I don't have windows to test right now, I develop on linux. I'll check it out on a friend later today. Some screenshots would also be useful as I'm not quite sure I understand what double shadow means

**Comment by wizgrav** [comment]
Nice demo btw, I think the shadow issue is not caused by effects the console spews out

```
THREE.WebGLShadowMap: Oi has no shadow.
```
which is a three problem

I'm not sure what the issue actually is though without some screenshots

**Comment by mike-hor** [comment]
first，thank for your reply
look this have double image （sorry,I had a problem with my statement before）
![image](https://user-images.githubusercontent.com/17822235/28193924-45fff3c0-6873-11e7-899b-e997c06a0d87.png)
![image](https://user-images.githubusercontent.com/17822235/28193934-57fd30d8-6873-11e7-9543-62e97a2d6b96.png)
I turn off the effect ,but all is normal
the problem just in win10,at least

**Comment by wizgrav** [comment]
Hey sorry for the long delay, I recently changed job(and country) and was kind of tied down. I now have a win10 setup and checked your demo. Your issue is one of poor depth buffer precision. You can work around that by adjusting your camera's near plane, when I set it at 0.2 instead of 0.02 it seems to work ok

**Comment by wizgrav** [comment]
thanks, things are progressing nicely :)
